# Generated by Django 5.1.3 on 2024-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementApp', '0004_alter_task_description_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN-PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=15, null=True),
        ),
    ]
